### ISSUE TITLE
g2/3.5.1 compilation failure on wcoss2 due to jasper calls

### ISSUE THREAD

**Issue by rgrumbine** [NOAA-EMC/NCEPLIBS-g2#841]
In trying to link my code for creating a grib2 file (which works with g2/3.4.5), I get a large number of error messages from jasper references from g2/3.5.1.

+ make
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.a(jpg_dec.c.o): in function `jpg_decode':
jpg_dec.c:(.text+0x237): undefined reference to `jpeg_std_error'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_dec.c:(.text+0x251): undefined reference to `jpeg_CreateDecompress'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_dec.c:(.text+0x261): undefined reference to `jpeg_stdio_src'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_dec.c:(.text+0x273): undefined reference to `jpeg_read_header'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_dec.c:(.text+0x323): undefined reference to `jpeg_start_decompress'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_dec.c:(.text+0x48f): undefined reference to `jpeg_read_scanlines'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_dec.c:(.text+0x4dc): undefined reference to `jpeg_finish_decompress'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_dec.c:(.text+0x4e9): undefined reference to `jpeg_destroy_decompress'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.a(jpg_enc.c.o): in function `jpg_encode':
jpg_enc.c:(.text+0x2d8): undefined reference to `jpeg_std_error'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x2f2): undefined reference to `jpeg_CreateCompress'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x302): undefined reference to `jpeg_stdio_dest'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x354): undefined reference to `jpeg_set_defaults'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x3a9): undefined reference to `jpeg_set_quality'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x3b6): undefined reference to `jpeg_default_colorspace'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x3c8): undefined reference to `jpeg_start_compress'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x547): undefined reference to `jpeg_write_scanlines'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x578): undefined reference to `jpeg_finish_compress'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: jpg_enc.c:(.text+0x585): undefined reference to `jpeg_destroy_compress'
make: *** [makefile:20: seaice_grib2] Error 1

The build versions are:

export envvar_ver=1.0

export intel_ver=19.1.3.304
export craype_ver=2.7.17
export PrgEnv_intel_ver=8.3.3
export cray_mpich_ver=8.1.19

export prod_envir_ver=2.0.6
export prod_util_ver=2.0.14

export w3emc_ver=2.12.0
export bacio_ver=2.4.1

export bufr_ver=12.2.0

#export g2_ver=3.4.5
export g2_ver=3.5.1
export jasper_ver=2.0.25
export libpng_ver=1.6.37
export zlib_ver=1.2.11

export hdf5_ver=1.10.6
export netcdf_ver=4.7.4

The source code is in /lfs/h2/emc/couple/save/rg/rgdev//seaice_analysis.v4.5.2/sorc/general/seaice_grib2.fd
along with makefile. the file 'makeall.mk' from 2 levels up is also  #needed.

This might be related to:
#826

**Comment by aerorahul** [comment]
@rgrumbine 
Try loading `libjpeg/9c`

**Comment by rgrumbine** [comment]
No change to the errors. Don't know how I misread jpeg as jasper.

**Comment by rgrumbine** [comment]
@aerorahul Should I change from intel/19.1.3.304 to intel-oneapi/2022.2.0.262 ?
